Change `pre-release.yml` for multi-platform builds
qBraid/pyqasm pull request #99
Opened 2024-12-03 13:26 UTC by TheGupta2012

## Summary of changes
* Added platform specific builds in `pre-release.yaml`
* Updated the `pre_build.sh` script to detect whether we are in pre-release, if yes, then change the version of the toml file to dev version.
*  Updated the `CIBW_BEFORE_BUILD` command to include the project name as an argument.

2024-12-03 16:26 UTC, ryanhill1 requested changes
With these updates, we no longer need the `create_dev_build.sh` script, right?

2024-12-03 18:30 UTC, TheGupta2012 commented
Yea, idts that the script would be needed.

The only thing which is unclear to me is how the pre-release version numbers would be tracked. For instance, say we have published `v0.1.0-a1`. Once we trigger the pre-release flow, how will it know that the next version to be published is `v0.1.0-a2` if the toml version stays at `v0.1.0-alpha`?

2024-12-03 18:31 UTC, TheGupta2012 commented on bin/cibw/pre_build.sh
Yep

2024-12-03 20:24 UTC, ryanhill1 commented
@TheGupta2012 It does so using [qbraid_core.system.versions.get_latest_package_version()](https://github.com/qBraid/qbraid-core/blob/v0.1.29/qbraid_core/system/versions.py#L167) with the option `prerelease=True`. This function makes a `GET` request to PyPI, and gets back a list of all of the releases for the given package, and is used as a helper within [qbraid_core.system.versions.get_prerelease_version()](https://github.com/qBraid/qbraid-core/blob/v0.1.29/qbraid_core/system/versions.py#L332). And then if the `pyproject.toml` version ends in `-alpha`, we get that latest "alpha" release matching that version and bump it by one. Same thing for "beta" and "rc". Or if no pre-releases for that marker exist yet, we set it to 0.

2024-12-04 05:51 UTC, TheGupta2012 commented on bin/cibw/pre_build.sh
Although we can make it optional, for consistency in the workflows I've provided it in both `main` and `release`

2024-12-04 20:45 UTC, ryanhill1 approved these changes

2024-12-05 05:52 UTC, TheGupta2012 commented
@ryanhill1 have also added the change for `sdist` version bump

2024-12-05 05:55 UTC, merged